### ISSUE TITLE
Problem with run application

### ISSUE THREAD

**Issue by pglez82** [alessandrococco/BangleApps#6]
Ciao @alessandrococco .

I suppose you are the creator of the run application. I was trying it yesterday in banglejs1 and it looks great. The problem that I found is that after pressing BTN2 to start and getting a gps fix, the app does not refresh the screen. It is like blocked until I press again BTN2 and it shows me some data of the run.

Is this expected or something is working wrong for me?

Regards,
Pablo

**Comment by alessandrococco** [comment]
Hi @pglez82,

> I suppose you are the creator of the run application. 

Sorry but I'm not the creator of the `run` app (I never used it). The only change I did is [remove this line](https://github.com/espruino/BangleApps/commit/42c2b5c8a2913172032e2ad3b3d0b9bee0ff5ea7#diff-19265c9fdf32e6ac7d17162aae32560018710e2ed0c296759657b34d4ab2ce93) in a big PR.

You shold open an issue in the [official repository](https://github.com/espruino/BangleApps/issues) ;-)

**Comment by pglez82** [comment]
Ok! Sorry for bothering you. I'll write in the official repository.
